<?php

namespace BoosterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitizenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitizenRepository extends EntityRepository
{
}
