<?php

namespace BoosterBundle\Repository;

/**
 * ExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertRepository extends \Doctrine\ORM\EntityRepository
{
}
