<?php

namespace BoosterBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * NeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeedsRepository extends EntityRepository
{
}
